/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Contact
         * @description Send a message. Limited to 3 per hour and 6 per day per visitor.
         */
        post: operations["post_contact_api_contact_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description Dashboard tiles: last run, last success, totals, recent trend and queue state.
         */
        get: operations["get_summary_api_pipeline_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Results
         * @description Measured results per drop (latest successful run of each), for the project page.
         */
        get: operations["get_results_api_pipeline_results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Runs */
        get: operations["get_runs_api_pipeline_runs_get"];
        put?: never;
        /**
         * Post Run
         * @description Queue a pipeline run. Limited per visitor and by overall queue capacity.
         */
        post: operations["post_run_api_pipeline_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_pipeline_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/runs/{run_id}/quarantine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quarantine */
        get: operations["get_quarantine_api_pipeline_runs__run_id__quarantine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenarios */
        get: operations["get_scenarios_api_pipeline_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/drops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Drops */
        get: operations["get_drops_api_pipeline_drops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/reasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Reasons
         * @description Every reason code the validator can assign, with its explanation.
         */
        get: operations["get_reasons_api_pipeline_reasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ComponentStatus */
        ComponentStatus: {
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "operational" | "degraded" | "down";
            /** Detail */
            detail: string;
        };
        /** ContactAccepted */
        ContactAccepted: {
            /**
             * Received
             * @default true
             */
            received: boolean;
        };
        /** ContactIn */
        ContactIn: {
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Company */
            company?: string | null;
            /**
             * Topic
             * @default project
             */
            topic: string;
            /** Message */
            message: string;
            /**
             * Website
             * @description Leave empty
             */
            website?: string | null;
        };
        /** DqOut */
        DqOut: {
            /** Check Name */
            check_name: string;
            /** Dimension */
            dimension: string;
            /** Stage */
            stage: string;
            /** Severity */
            severity: string;
            /** Passed */
            passed: boolean;
            /** Observed */
            observed: number | null;
            /** Threshold */
            threshold: string;
            /** Weight */
            weight: number;
            /** Detail */
            detail: string;
        };
        /** DropOut */
        DropOut: {
            /** Key */
            key: string;
            /** Rows */
            rows: number;
            /** Loaded */
            loaded: boolean;
            /** First Loaded At */
            first_loaded_at: string | null;
            /** Times Processed */
            times_processed: number;
        };
        /** DropResult */
        DropResult: {
            /** Drop Key */
            drop_key: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Finished At */
            finished_at: string | null;
            /** Rows Read */
            rows_read: number;
            /** Rows Rejected */
            rows_rejected: number;
            /** Rows Deduplicated */
            rows_deduplicated: number;
            /** Rows Published */
            rows_published: number;
            /** Dq Score */
            dq_score: number | null;
            /** Duration Ms */
            duration_ms: number | null;
        };
        /** DurationStats */
        DurationStats: {
            /** Median Ms */
            median_ms: number | null;
            /** P95 Ms */
            p95_ms: number | null;
            /** Max Ms */
            max_ms: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LogOut */
        LogOut: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Level */
            level: string;
            /** Event */
            event: string;
            /** Fields */
            fields: {
                [key: string]: unknown;
            };
        };
        /** QuarantinePage */
        QuarantinePage: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["QuarantineRowOut"][];
        };
        /** QuarantineRowOut */
        QuarantineRowOut: {
            /** Line Number */
            line_number: number;
            /** Reason Code */
            reason_code: string;
            /** Severity */
            severity: string;
            /** Raw */
            raw: {
                [key: string]: unknown;
            };
        };
        /** ReasonCount */
        ReasonCount: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Severity */
            severity: string;
            /** Explanation */
            explanation: string;
            /** Count */
            count: number;
        };
        /**
         * ResultsOut
         * @description Measured results: the latest successful run of every loaded drop.
         */
        ResultsOut: {
            /** Drops */
            drops: components["schemas"]["DropResult"][];
            totals: components["schemas"]["ResultsTotals"];
            duration: components["schemas"]["DurationStats"];
            /** Environment */
            environment: {
                [key: string]: unknown;
            } | null;
            /** Runs Succeeded */
            runs_succeeded: number;
            /** Runs Failed */
            runs_failed: number;
        };
        /** ResultsTotals */
        ResultsTotals: {
            /** Drops */
            drops: number;
            /** Rows Read */
            rows_read: number;
            /** Rows Rejected */
            rows_rejected: number;
            /** Rows Deduplicated */
            rows_deduplicated: number;
            /** Rows Published */
            rows_published: number;
        };
        /** RunAccepted */
        RunAccepted: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Status */
            status: string;
            /** Pending Runs */
            pending_runs: number;
        };
        /** RunDetailOut */
        RunDetailOut: {
            run: components["schemas"]["RunOut"];
            /** Steps */
            steps: components["schemas"]["StepOut"][];
            /** Checks */
            checks: components["schemas"]["DqOut"][];
            /** Reasons */
            reasons: components["schemas"]["ReasonCount"][];
            /** Warnings */
            warnings: components["schemas"]["ReasonCount"][];
            /** Logs */
            logs: components["schemas"]["LogOut"][];
            /** Environment */
            environment: {
                [key: string]: unknown;
            } | null;
            /**
             * Dq Formula
             * @default 100 × Σ(weight × passed) / Σ(weight); weights: gate 3, warn 2, info 1
             */
            dq_formula: string;
        };
        /** RunOut */
        RunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Scenario */
            scenario: string;
            /** Trigger */
            trigger: string;
            /** Simulated */
            simulated: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed";
            /** Drop Key */
            drop_key: string | null;
            /**
             * Queued At
             * Format: date-time
             */
            queued_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Rows Read */
            rows_read: number;
            /** Rows Accepted */
            rows_accepted: number;
            /** Rows Rejected */
            rows_rejected: number;
            /** Rows Deduplicated */
            rows_deduplicated: number;
            /** Rows Warned */
            rows_warned: number;
            /** Rows Inserted */
            rows_inserted: number;
            /** Rows Unchanged */
            rows_unchanged: number;
            /** Source Retries */
            source_retries: number;
            /** Dq Score */
            dq_score: number | null;
            /** Failure Step */
            failure_step: string | null;
            /** Error Message */
            error_message: string | null;
            /** Note */
            note: string | null;
        };
        /** RunRequest */
        RunRequest: {
            /** Scenario */
            scenario: string;
        };
        /** ScenarioOut */
        ScenarioOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Simulated */
            simulated: boolean;
            /** Expected */
            expected: string;
        };
        /** StatusOut */
        StatusOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "operational" | "degraded" | "down";
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Components */
            components: components["schemas"]["ComponentStatus"][];
            /** Busy With */
            busy_with: string | null;
        };
        /** StepOut */
        StepOut: {
            /** Position */
            position: number;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Duration Ms */
            duration_ms: number;
            /** Rows In */
            rows_in: number | null;
            /** Rows Out */
            rows_out: number | null;
            /** Detail */
            detail: {
                [key: string]: unknown;
            } | null;
        };
        /** SummaryOut */
        SummaryOut: {
            last_run: components["schemas"]["RunOut"] | null;
            last_success: components["schemas"]["RunOut"] | null;
            /** Runs Total */
            runs_total: number;
            /** Failures Recent */
            failures_recent: number;
            /** Recent Window */
            recent_window: number;
            /** Drops Loaded */
            drops_loaded: number;
            /** Drops Total */
            drops_total: number;
            warehouse: components["schemas"]["WarehouseStats"];
            /** Pending Runs */
            pending_runs: number;
            /** Lease Holder */
            lease_holder: string | null;
            /** Trend */
            trend: components["schemas"]["TrendPoint"][];
        };
        /** TrendPoint */
        TrendPoint: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
            /** Scenario */
            scenario: string;
            /** Drop Key */
            drop_key: string | null;
            /** Dq Score */
            dq_score: number | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Rows Read */
            rows_read: number;
            /** Rows Rejected */
            rows_rejected: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WarehouseStats */
        WarehouseStats: {
            /** Invoice Lines */
            invoice_lines: number;
            /** Invoices */
            invoices: number;
            /** Customers */
            customers: number;
            /** Products */
            products: number;
            /** Net Revenue Gbp */
            net_revenue_gbp: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOut"];
                };
            };
        };
    };
    post_contact_api_contact_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_pipeline_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryOut"];
                };
            };
        };
    };
    get_results_api_pipeline_results_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultsOut"];
                };
            };
        };
    };
    get_runs_api_pipeline_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_run_api_pipeline_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_pipeline_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quarantine_api_pipeline_runs__run_id__quarantine_get: {
        parameters: {
            query?: {
                reason?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuarantinePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenarios_api_pipeline_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioOut"][];
                };
            };
        };
    };
    get_drops_api_pipeline_drops_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DropOut"][];
                };
            };
        };
    };
    get_reasons_api_pipeline_reasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    }[];
                };
            };
        };
    };
}
