"""Publish read-only per-project mirror repositories from this monorepo.

The monorepo is the only place anyone commits. For each project listed in ``MIRRORS`` this
script assembles the project with the shared packages it uses into a directory and, with
``--push``, commits it as a snapshot onto ``github.com/<owner>/<repo>`` so each project has
its own browsable repository. Run by ``.github/workflows/mirror.yml`` after a deploy.

    python scripts/mirror_projects.py --out build/mirrors            # assemble only
    python scripts/mirror_projects.py --out build/mirrors --push      # needs MIRROR_TOKEN
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OWNER = os.environ.get("MIRROR_OWNER", "uzairazhar89")
MONOREPO = f"https://github.com/{OWNER}/reluai"


@dataclass(frozen=True)
class Mirror:
    project: str  # directory under projects/
    repo: str  # mirror repository name
    title: str
    packages: tuple[str, ...]  # shared packages under packages/ the project imports


MIRRORS = (
    Mirror(
        project="pipeline-observatory",
        repo="reluai-pipeline-observatory",
        title="Data Pipeline Observatory",
        packages=("platform-core", "datasets"),
    ),
)

ALWAYS = ("LICENSE", "artifacts/manifest.yaml", ".gitattributes", ".editorconfig")
IGNORE = shutil.ignore_patterns(
    "__pycache__", "*.pyc", ".pytest_cache", ".mypy_cache", "*.egg-info"
)
GIT = shutil.which("git") or "git"


def git(*args: str, cwd: Path) -> str:
    # Arguments are constants from this script, never user input.
    return subprocess.run(  # noqa: S603
        [GIT, *args], cwd=cwd, check=True, capture_output=True, text=True
    ).stdout.strip()


def header(m: Mirror, sha: str) -> str:
    return (
        f"> **Read-only mirror.** This repository is published automatically from "
        f"[{OWNER}/reluai]({MONOREPO}) (`projects/{m.project}` at "
        f"[`{sha[:12]}`]({MONOREPO}/tree/{sha}/projects/{m.project})). Changes, issues and "
        f"the full stack (API, migrations, website, infrastructure) live there.\n\n"
    )


def workspace_pyproject(m: Mirror) -> str:
    members = [f'"projects/{m.project}"', *(f'"packages/{p}"' for p in m.packages)]
    return (
        "# Generated by scripts/mirror_projects.py in the monorepo. Do not edit here.\n"
        "[project]\n"
        f'name = "{m.repo}-workspace"\n'
        'version = "0.0.0"\n'
        'requires-python = ">=3.12"\n'
        "dependencies = []\n\n"
        "[tool.uv]\npackage = false\n\n"
        "[tool.uv.workspace]\n"
        f"members = [{', '.join(members)}]\n"
    )


def assemble(m: Mirror, out: Path, sha: str) -> Path:
    dest = out / m.repo
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)
    shutil.copytree(ROOT / "projects" / m.project, dest / "projects" / m.project, ignore=IGNORE)
    for pkg in m.packages:
        shutil.copytree(ROOT / "packages" / pkg, dest / "packages" / pkg, ignore=IGNORE)
    for rel in ALWAYS:
        src = ROOT / rel
        if src.exists():
            (dest / rel).parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dest / rel)
    readme = (ROOT / "projects" / m.project / "README.md").read_text(encoding="utf-8")
    (dest / "README.md").write_text(header(m, sha) + readme, encoding="utf-8")
    (dest / "pyproject.toml").write_text(workspace_pyproject(m), encoding="utf-8")
    (dest / ".gitignore").write_text("__pycache__/\n.venv/\ndata/\n.env\n", encoding="utf-8")
    return dest


def push(m: Mirror, assembled: Path, sha: str, token: str) -> None:
    remote = f"https://x-access-token:{token}@github.com/{OWNER}/{m.repo}.git"
    work = assembled.with_name(assembled.name + ".git-work")
    if work.exists():
        shutil.rmtree(work)
    clone = subprocess.run(  # noqa: S603
        [GIT, "clone", "--quiet", "--depth", "1", remote, str(work)],
        capture_output=True,
        text=True,
        check=False,
    )
    if clone.returncode != 0:
        print(f"skip {m.repo}: cannot clone (create the empty repository first?)", file=sys.stderr)
        return
    for child in work.iterdir():
        if child.name == ".git":
            continue
        if child.is_dir():
            shutil.rmtree(child)
        else:
            child.unlink()
    shutil.copytree(assembled, work, dirs_exist_ok=True)
    git("add", "--all", cwd=work)
    if not git("status", "--porcelain", cwd=work):
        print(f"{m.repo}: already up to date")
        return
    git(
        "-c",
        "user.name=reluai-mirror",
        "-c",
        "user.email=mirror@reluai.cloud",
        "commit",
        "--quiet",
        "-m",
        f"Mirror of {OWNER}/reluai@{sha[:12]}",
        cwd=work,
    )
    git("push", "--quiet", "origin", "HEAD", cwd=work)
    print(f"{m.repo}: pushed snapshot of {sha[:12]}")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=ROOT / "build" / "mirrors")
    parser.add_argument("--push", action="store_true")
    args = parser.parse_args(argv)

    sha = git("rev-parse", "HEAD", cwd=ROOT)
    token = os.environ.get("MIRROR_TOKEN", "")
    if args.push and not token:
        print("MIRROR_TOKEN is not set; assembling without pushing", file=sys.stderr)
    for m in MIRRORS:
        assembled = assemble(m, args.out, sha)
        print(f"assembled {m.repo} in {assembled}")
        if args.push and token:
            push(m, assembled, sha, token)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
